config/routes.rb
Rails.application.routes.draw do
  mount Api::Base, at: "/"

  draw(:admin)
  draw(:users)
  draw(:current_stable)
  draw(:horses)
  draw(:racing)

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_error", via: :all

  resources :stables, only: %i[index show]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker

  unauthenticated do
    root to: "pages#home"
  end

  authenticated :user do
    root to: "stables#show", as: :authenticated_root
  end
end

# == Route Map
#
# Routes for application:
#                                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#                                 api_base        /                                                                                                 Api::Base
#                        admin_impersonate DELETE /admin/impersonate(.:format)                                                                      admin/impersonates#destroy
#                                          POST   /admin/impersonate(.:format)                                                                      admin/impersonates#create
#                         new_user_session GET    /login(.:format)                                                                                  users/sessions#new
#                             user_session POST   /login(.:format)                                                                                  users/sessions#create
#                     destroy_user_session DELETE /logout(.:format)                                                                                 users/sessions#destroy
#                        new_user_password GET    /forgot-password/new(.:format)                                                                    devise/passwords#new
#                       edit_user_password GET    /forgot-password/edit(.:format)                                                                   devise/passwords#edit
#                            user_password PATCH  /forgot-password(.:format)                                                                        devise/passwords#update
#                                          PUT    /forgot-password(.:format)                                                                        devise/passwords#update
#                                          POST   /forgot-password(.:format)                                                                        devise/passwords#create
#                 cancel_user_registration GET    /cancel(.:format)                                                                                 users/registrations#cancel
#                    new_user_registration GET    /join(.:format)                                                                                   users/registrations#new
#                   edit_user_registration GET    /edit(.:format)                                                                                   users/registrations#edit
#                        user_registration PATCH  /                                                                                                 users/registrations#update
#                                          PUT    /                                                                                                 users/registrations#update
#                                          DELETE /                                                                                                 users/registrations#destroy
#                                          POST   /                                                                                                 users/registrations#create
#                    new_user_confirmation GET    /confirm-account/new(.:format)                                                                    devise/confirmations#new
#                        user_confirmation GET    /confirm-account(.:format)                                                                        devise/confirmations#show
#                                          POST   /confirm-account(.:format)                                                                        devise/confirmations#create
#                          new_user_unlock GET    /unlock/new(.:format)                                                                             devise/unlocks#new
#                              user_unlock GET    /unlock(.:format)                                                                                 devise/unlocks#show
#                                          POST   /unlock(.:format)                                                                                 devise/unlocks#create
#                               activation GET    /activation_required(.:format)                                                                    pages#activation
#                                    users GET    /users(.:format)                                                                                  users#index
#                                          POST   /users(.:format)                                                                                  users#create
#                                 new_user GET    /users/new(.:format)                                                                              users#new
#                                edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
#                                     user GET    /users/:id(.:format)                                                                              users#show
#                                          PATCH  /users/:id(.:format)                                                                              users#update
#                                          PUT    /users/:id(.:format)                                                                              users#update
#                                          DELETE /users/:id(.:format)                                                                              users#destroy
#                            notifications GET    /notifications(.:format)                                                                          notifications#index
#                             notification PATCH  /notifications/:id(.:format)                                                                      notifications#update
#                                          PUT    /notifications/:id(.:format)                                                                      notifications#update
#                                          DELETE /notifications/:id(.:format)                                                                      notifications#destroy
#                                 settings POST   /settings(.:format)                                                                               settings#create
#                              new_setting GET    /settings/new(.:format)                                                                           settings#new
#                           pwa_web_pushes POST   /pwa/web_pushes(.:format)                                                                         pwa/web_pushes#create
#                       push_subscriptions POST   /push_subscriptions(.:format)                                                                     current_stable/push_subscriptions#create
#                     change_notifications POST   /push_subscriptions/change(.:format)                                                              current_stable/push_subscriptions#change
#                      edit_current_stable GET    /stable/edit(.:format)                                                                            stables#edit
#                           current_stable GET    /stable(.:format)                                                                                 stables#show
#                                          PATCH  /stable(.:format)                                                                                 stables#update
#                                          PUT    /stable(.:format)                                                                                 stables#update
#                           stable_budgets GET    /stable/budgets(.:format)                                                                         current_stable/budgets#index
#                            stable_horses GET    /stable/horses(.:format)                                                                          current_stable/horses#index
#                        edit_stable_horse GET    /stable/horses/:id/edit(.:format)                                                                 current_stable/horses#edit
#                             stable_horse GET    /stable/horses/:id(.:format)                                                                      current_stable/horses#show
#                                          PATCH  /stable/horses/:id(.:format)                                                                      current_stable/horses#update
#                                          PUT    /stable/horses/:id(.:format)                                                                      current_stable/horses#update
#                            stable_leases GET    /stable/leases(.:format)                                                                          current_stable/leases#index

app/models/horses/appearance.rb
require "image_processing/vips"

module Horses
  class Appearance < ApplicationRecord
    include ActionView::Helpers::TextHelper

    self.table_name = "horse_appearances"

    belongs_to :horse, class_name: "Horse"

    validates :birth_height, :color, :current_height, :max_height, presence: true
    validates :current_height, comparison: { greater_than_or_equal_to: :birth_height }
    validates :max_height, comparison: { greater_than_or_equal_to: :current_height }
    validates :color, inclusion: { in: Color::VALUES.keys.map(&:to_s) }

    validates :face_marking, inclusion: { in: FaceMarking::VALUES.keys.map(&:to_s) }, allow_blank: true
    validates :face_image, absence: true, unless: :face_marking
    validates :face_image, presence: true, if: :face_marking

    validates :rf_leg_marking, inclusion: { in: LegMarking::VALUES.keys.map(&:to_s) }, allow_blank: true
    validates :rf_leg_image, presence: true, if: :rf_leg_marking
    validates :rf_leg_image, absence: true, unless: :rf_leg_marking

    validates :lf_leg_marking, inclusion: { in: LegMarking::VALUES.keys.map(&:to_s) }, allow_blank: true
    validates :lf_leg_image, presence: true, if: :lf_leg_marking
    validates :lf_leg_image, absence: true, unless: :lf_leg_marking

    validates :rh_leg_marking, inclusion: { in: LegMarking::VALUES.keys.map(&:to_s) }, allow_blank: true
    validates :rh_leg_image, presence: true, if: :rh_leg_marking
    validates :rh_leg_image, absence: true, unless: :rh_leg_marking

    validates :lh_leg_marking, inclusion: { in: LegMarking::VALUES.keys.map(&:to_s) }, allow_blank: true
    validates :lh_leg_image, presence: true, if: :lh_leg_marking
    validates :lh_leg_image, absence: true, unless: :lh_leg_marking

    delegate :gender, to: :horse

    def image(max_width: 500, max_height: 500)
      return @image if @image

      result = GenerateHorseImageService.call(horse_id: horse.id, max_height:, max_width:)
      if result.success?
        @image = result.payload
      else
        raise result.error
      end
    end

    def height_display
      I18n.t("horse.height", height: current_height)
    end

    def markings_description
      if no_markings?
        I18n.t("horse.markings.none").titleize
      else
        markings = []
        markings << I18n.t("horse.markings.#{face_marking}").titleize if face_marking.present?
        all_legs = [rh_leg_marking, lf_leg_marking, rh_leg_marking, lh_leg_marking].compact
        if all_legs.size == 4 && all_legs.uniq.size == 1
          Rails.logger.info "same markings everywhere"
          markings << pluralize(4, all_legs.first.titleize)
        else
          markings << "LF #{lf_leg_marking.titleize}" if lf_leg_marking.present?
          markings << "RF #{rf_leg_marking.titleize}" if rf_leg_marking.present?
          markings << "LH #{lh_leg_marking.titleize}" if lh_leg_marking.present?
          markings << "RH #{rh_leg_marking.titleize}" if rh_leg_marking.present?
        end
        markings.join(", ")
      end
    end

    def no_markings?
      [rf_leg_marking, lf_leg_marking, rh_leg_marking, lh_leg_marking, face_marking].all?(&:blank?)
    end
  end
end

# == Schema Information
#
# Table name: horse_appearances
# Database name: primary
#
#  id                                                                                                                                                                                                                     :bigint           not null, primary key
#  birth_height                                                                                                                                                                                                           :decimal(4, 2)    default(0.0), not null
#  color(bay, black, blood_bay, blue_roan, brown, chestnut, dapple_grey, dark_bay, dark_grey, flea_bitten_grey, grey, light_bay, light_chestnut, light_grey, liver_chestnut, mahogany_bay, red_chestnut, strawberry_roan) :enum             default("bay"), not null
#  current_height                                                                                                                                                                                                         :decimal(4, 2)    default(0.0), not null
#  face_image                                                                                                                                                                                                             :string
#  face_marking(bald_face, blaze, snip, star, star_snip, star_stripe, star_stripe_snip, stripe, stripe_snip)                                                                                                              :enum
#  lf_leg_image                                                                                                                                                                                                           :string
#  lf_leg_marking(coronet, ermine, sock, stocking)                                                                                                                                                                        :enum
#  lh_leg_image                                                                                                                                                                                                           :string
#  lh_leg_marking(coronet, ermine, sock, stocking)                                                                                                                                                                        :enum
#  max_height                                                                                                                                                                                                             :decimal(4, 2)    default(0.0), not null
#  rf_leg_image                                                                                                                                                                                                           :string
#  rf_leg_marking(coronet, ermine, sock, stocking)                                                                                                                                                                        :enum
#  rh_leg_image                                                                                                                                                                                                           :string
#  rh_leg_marking(coronet, ermine, sock, stocking)                                                                                                                                                                        :enum
#  created_at                                                                                                                                                                                                             :datetime         not null
#  updated_at                                                                                                                                                                                                             :datetime         not null
#  horse_id                                                                                                                                                                                                               :bigint           not null, uniquely indexed
#
# Indexes
#
#  index_horse_appearances_on_horse_id  (horse_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (horse_id => horses.id) ON DELETE => cascade ON UPDATE => cascade
#

app/views/horses/_dam_foal_list.html.slim
/# locals: (horse:)
.mx-auto.overflow-x-auto.rounded-box.border.border-base-content/5.bg-base-100.w-full[
  class="sm:w-3/4 dark:border-neutral-100"
]
  table.table.table-sm
    thead
      tr
        th.uppercase= t(".name")
        th.uppercase= t(".year_of_birth")
        th.uppercase= t(".gender")
        th.uppercase= t(".sire")
        th.uppercase= t(".status")
        th.uppercase= t(".record")
    tbody
      - horse.foals.born.order(date_of_birth: :asc).each do |foal|
        - pedigree = Horses::PedigreeDisplayService.new(foal)
        tr
          td= link_to (foal.name || t("horse.unnamed")), horse_path(foal)
          td= foal.date_of_birth.year
          td= foal.gender.titleize
          td= pedigree.sire_display(tag: true)
          td= foal.status.titleize
          td
            - if foal.stillborn?
              em= t("horse.type.stillborn").titleize
            - else
              = foal.track_record
      - unborn_foal = horse.foals.unborn.order(date_of_birth: :asc).first
      - if unborn_foal
        tr
          td= t("horse.in_foal").titleize
          td= unborn_foal.date_of_birth.year
          td= t("common.dash")
          td= link_to unborn_foal.sire.name, horse_path(unborn_foal.sire)
          td colspan=2
            = "due date here"

app/views/horses/_dam_foal_summary.slim
/# locals: (horse:)
- record = horse.broodmare_foal_record || horse.build_broodmare_foal_record
.mx-auto.overflow-x-auto.rounded-box.border.border-base-content/5.bg-base-100.w-full[
  class="sm:w-1/2 dark:border-neutral-100/50"
]
  table.table.table-sm
    tbody
      tr
        th.uppercase.text-center
          = t(".foals")
        th.uppercase.text-center
          = t(".breed_ranking")
      tr.text-center
        td
          = record.born_foals_count
          - if record.stillborn_foals_count.positive?
            = "&nbsp;".html_safe
            em= "(#{record.stillborn_foals_count} Stillborn)"
        td= record.breed_ranking_string
      tr
        th.uppercase.text-center
          = t(".racers")
        th.uppercase.text-center
          = t(".winners")
      tr
        td.text-center
          = record.raced_foals_string
        td.text-center
          = record.winning_foals_string
      tr
        th.uppercase.text-center
          = t(".stakes_winners")
        th.uppercase.text-center
          = t(".multi_stakes_winners")
      tr
        td.text-center
          = record.stakes_winning_foals_string
        td.text-center
          = record.multi_stakes_winning_foals_string
      tr
        th.uppercase.text-center
          = t(".millionaires")
        th.uppercase.text-center
          = t(".average_earnings")
      tr
        td.text-center
          = record.millionaire_foals_string
        td.text-center
          = record.earnings_string

app/views/horses/_edit_name_form.html.slim
= form_with model: horse, scope: :horse, url: horse_path(horse.slug), data: { turbo_frame: "_top" } do |f|
  fieldset.fieldset.bg-base-100.border-base-300.rounded-box.border.py-2.w-xs.inline
    .join
      = f.text_field :name, class: 'input join-item w-auto', required: true, placeholder: t(".name_hint", count: Config::Horses.max_name_length)
      = render Ui::SubmitButton::Component.new(form: f, extra_classes: "join-item", text: t("common.actions.save"))
    - if horse.errors[:name]
      p.text-error= horse.errors.where(:name).map(&:full_message).join(', ')
  = render Ui::ButtonizedLink::Component.new(url: horse_path(horse.slug), color: :error, style: :outline, extra_classes: "p-2 mt-2 align-top", data: { turbo_frame: "_top" }) do
    = t("common.actions.cancel")

app/views/horses/_info.html.slim
/# locals: (horse:)
.overflow-x-auto
  table.table
    tbody
      - if Current.user&.admin? || true_user&.admin?
        tr
          th= t(".id")
          td
            = horse.id
            = t(".legacy_id", id: horse.legacy_id)
      tr
        th= t(".name")
        td
          = turbo_frame_tag :horse_name do
            = horse.name || t("horse.unnamed")
            - if Horses::HorsePolicy.new(Current.user, horse).edit_name?
              = render Ui::ButtonizedLink::Component.new(url: edit_name_horse_path(horse), style: :outline, size: :small, extra_classes: "ml-2", http_method: :get) do
                = t("common.actions.edit")
      tr
        th= t(".date_of_birth")
        td
          = l(horse.date_of_birth)
          - unless horse.dead?
            = "&nbsp;".html_safe
            = "(#{horse.age}yo)"
      - if horse.dead?
        tr
          th= t(".date_of_death")
          td
            = l(horse.date_of_death)
            = "&nbsp;".html_safe
            = "(#{horse.age}yo)"
      tr
        th= t(".location_bred")
        td= horse.location_bred_name
      tr
        th= t(".gender")
        td= horse.gender.titleize
      tr
        th= t(".status")
        td= horse.status.titleize
      tr
        th= t(".color")
        td= horse.appearance.color.titleize
      tr
        th= t(".markings")
        td= horse.appearance.markings_description
      tr
        th= t(".height")
        td= horse.appearance.height_display
      tr
        th= t(".breeder")
        td= link_to horse.breeder.name, stable_path(horse.breeder), target: "_top"
      tr
        th= t(".owner")
        td= link_to horse.owner.name, stable_path(horse.owner), target: "_top"
      - unless horse.dead?
        - if horse.racehorse? || horse.broodmare?
          tr
            th= t(".location")
            td
              - if horse.racehorse?
                = horse.racing.current_location_name
                - if horse.racing.in_transit?
                  em.ml-2= t(".in_transit", date: l(horse.racing.last_shipment.arrival_date))
              - else
                = horse.broodmare.current_location_name
                - if horse.broodmare.in_transit?
                  em.ml-2= t(".in_transit", date: l(horse.broodmare.last_shipment.arrival_date))
        - if horse.current_lease&.persisted?
          = turbo_frame_tag dom_id(horse) do
            tr
              th= t(".lease_status")
              td
                - lease = horse.current_lease
                - leaser_stable = link_to lease.leaser.name, stable_path(lease.leaser), target: "_top"
                = I18n.t("horse.leased_html", stable: leaser_stable, date: l(lease.end_date)).html_safe
                - if lease.termination_request
                  p.ml-2.badge.badge-outline.badge-info= t(".lease_termination_requested")
        - else
          tr
            th= t(".sale_status")
            td
              - if (lease = horse.lease_offer)&.persisted?
                = t(".offered_for_lease", duration: lease.duration_months, fee: Game::MoneyFormatter.new(lease.fee).to_s)
              - elsif (sale = horse.sale_offer)&.persisted?
                - if [horse.owner, sale.buyer].include?(Current.stable) || sale.buyer.nil?
                  = t(".offered_for_sale", price: Game::MoneyFormatter.new(sale.price).to_s)
                - else
                  = t(".offered_for_sale_private_html")
              - elsif (auction_horse = horse.auction_horse)&.persisted?
                - auction = auction_horse.auction
                = t(".consigned_to_auction")
                = "&nbsp;".html_safe
                = link_to auction.title, auction_path(auction), target: "_top"
              - else
                = t(".not_for_sale")
      tr
        th= t(".track_record")
        td= horse.track_record || t("horse.unraced")
      - if horse.racehorse?
        tr
          th= t(".last_race")
          td Not Yet Added
        tr
          th= t(".next_race")
          td Not Yet Added
        tr
          th= t(".scheduled_race")
          td Not Yet Added
      - if Horses::Status::BREEDING_STATUSES.include?(horse.status)
        tr
          th= t(".breeding_record")
          td
            - if horse.female?
              = horse.broodmare.breed_ranking_string
            - else
              = horse.stud.breed_ranking_string
      - if Horses::Status::FEMALE_BREEDING_STATUSES.include?(horse.status)
        tr
          th= t(".last_foal")
          td
            - if horse.foals.born.present?
              - last_dob = horse.foals.born.order(date_of_birth: :desc).pluck(:date_of_birth).first
              - horse.foals.born.where(date_of_birth: last_dob).find_each do |foal|
                - pedigree = Horses::PedigreeDisplayService.new(foal)
                span class="text-#{foal.gender}" = link_to foal.budget_name, horse_path(foal), data: { turbo_frame: "_top" }
                = " - "
                = t(".foal_info", year: l(foal.date_of_birth, format: :year_abbr), gender: foal.gender, sire: pedigree.sire_display(target: "_top")).html_safe
        tr
          th= t(".next_foal")
          td
            - if horse.next_foal.present?
              - stud = horse.next_foal.stud
              span
                = t(".in_foal", stud: link_to(stud.name, horse_path(stud))).html_safe
                = t(".due_date", date: l(horse.next_foal.due_date, format: :slashes))

app/views/horses/_races_mobile.html.slim
/# locals: (horse:)
.mx-auto.overflow-x-auto.border.rounded-md.w-full
  - if horse.annual_race_records.empty?
    table.table
      thead
        td.text-secondary-content.text-center= t(".unraced")
  - else
    .join.join-vertical.bg-base-100
      .collapse.collapse-arrow.join-item.border-base-300.border
        input type="radio" name="race-record" checked="checked"
        .collapse-title.font-semibold= t(".lifetime")
        .collapse-content.text-sm
          - record = horse.lifetime_race_record
          - if record
            table.table.table-zebra
              tbody
                tr
                  td= t(".starts")
                  td.text-right= record.starts_string
                tr
                  td= t(".wins")
                  td.text-right= record.wins_string
                tr
                  td= t(".seconds")
                  td.text-right= record.seconds_string
                tr
                  td= t(".thirds")
                  td.text-right= record.thirds_string
                tr
                  td= t(".fourths")
                  td.text-right= record.fourths_string
                tr
                  td= t(".earnings")
                  td.text-right= record.earnings_string
                tr
                  td= t(".points")
                  td.text-right= record.points

        - horse.annual_race_records.ordered.each do |record|
          - description = t(".race_year", age: record.year - horse.date_of_birth.year, year: record.year)
          .collapse.collapse-arrow.join-item.border-base-300.border
            input type="radio" name="race-record"
            .collapse-title.font-semibold= description
            .collapse-content.text-sm
              table.table.table-zebra
                tbody
                  tr
                    td= t(".starts")
                    td.text-right= record.starts_string
                  tr
                    td= t(".wins")
                    td.text-right= record.wins_string
                  tr
                    td= t(".seconds")
                    td.text-right= record.seconds_string
                  tr
                    td= t(".thirds")
                    td.text-right= record.thirds_string
                  tr
                    td= t(".fourths")
                    td.text-right= record.fourths_string
                  tr
                    td= t(".earnings")
                    td.text-right= record.earnings_string
                  tr
                    td= t(".points")
                    td.text-right= record.points

app/views/horses/_sire_foal_list.html.slim
/# locals: (horse:)
- unborn_foals = horse.stud_foals.unborn.order_by_dam.select(:date_of_birth, :dam_id)
.m-2.mx-auto.overflow-x-auto.rounded-box.border.bg-base-100.w-full.border-base-content/70[
  class="sm:w-3/4 dark:border-neutral-100"
]
  table.table.table-sm
    thead
      tr
        th.uppercase= t(".name")
        th.uppercase= t(".year_of_birth")
        th.uppercase= t(".gender")
        th.uppercase= t(".dam")
        th.uppercase= t(".status")
        th.uppercase= t(".record")
    tbody
      - horse.stud_foals.born.includes(:dam).order_by_yob.order(name: :asc).each do |foal|
        - pedigree = Horses::PedigreeDisplayService.new(foal)
        tr
          td= link_to (foal.name || t("horse.unnamed")), horse_path(foal)
          td= foal.date_of_birth.year
          td= foal.gender.titleize
          td= pedigree.dam_display(tag: true)
          td= foal.status.titleize
          td
            - if foal.stillborn?
              em= t("horse.type.stillborn").titleize
            - else
              = foal.track_record

    - unborn_foals.each do |unborn_foal|
      tr
        td= t("horse.foal_due").titleize
        td= unborn_foal.date_of_birth.year
        td= t("common.dash")
        td= link_to unborn_foal.dam.name, horse_path(unborn_foal.dam)
        td colspan=2
          = "due date here"

app/views/horses/edit.html.haml
- content_for :breadcrumbs do
  - success_classes = "btn btn-light btn-sm border border-success text-success text-decoration-none"
  = render Nav::Breadcrumbs::Component.new(links: [{ name: t("horses.index.title"), href: horses_path },
                                                   { name: horse.name, href: "#" }],
                                           actions: [{ name: "edit",
                                                       link: edit_horse_path(horse),
                                                       i18n_key: "common.edit",
                                                       user: current_user,
                                                       object: horse,
                                                       base_classes: success_classes,
                                                       classes: "ms-3 me-3",
                                                       responsive_classes: "w-100",
                                                       type: :link }])

= turbo_frame_tag @horse do
  = render "form", horse: @horse